### ISSUE TITLE
mergehex is used with more than 3 files

### ISSUE THREAD

**Issue by podkiva** [NRB-Tech/nRF5-cmake-scripts#4]
mergehex utility is used with 4 files when nRF5_addBootloaderSoftDeviceAppMergeTarget is invoked, should be done sequentially instead. The command in nRF5-cmake.cmake that causes the problem:

`
COMMAND ${MERGEHEX} -m ${BOOTLOADER_HEX} "${CMAKE_CURRENT_BINARY_DIR}/${EXECUTABLE_NAME}_bootloader_setting.hex" "${${SOFTDEVICE}_HEX_FILE}" "${CMAKE_CURRENT_BINARY_DIR}/${EXECUTABLE_NAME}.hex" -o "${OP_FILE}`

I suggest the following replacement:

`
COMMAND ${MERGEHEX} -m ${BOOTLOADER_HEX} "${CMAKE_CURRENT_BINARY_DIR}/${EXECUTABLE_NAME}_bootloader_setting.hex" "${${SOFTDEVICE}_HEX_FILE}" -o "${OP_FILE}"
`
`COMMAND ${MERGEHEX} -m "${CMAKE_CURRENT_BINARY_DIR}/${EXECUTABLE_NAME}.hex" "${OP_FILE}" -o "${OP_FILE}"
`

**Comment by nrbrook** [comment]
Why is this an issue? Mergehex accepts multiple input files - this works for me as it is

**Comment by podkiva** [comment]
Hmm, strange but for me it is not, and I have version 10.6.0. Also, from [that pdf](https://infocenter.nordicsemi.com/pdf/nRF5x_Command_Line_Tools_v1.0.pdf) I have red that it only accepts 3 files, and also I have tested it - it works only with 3 in my case.

I will update it tomorrow and see if the problem is in version.

**Comment by nrbrook** [comment]
Strange, what platform are you using? I'm using Mac.

**Comment by podkiva** [comment]
Ok, so it was the version - I have updated Nordic Command Line Tools from 10.6.0 to 10.12.1, and now mergehex works with more than 3 files.

I am on Ubuntu 18.04
